#!/bin/bash

echo -n "Enter java home [${JAVA_HOME}]: "

read CAT_JAVA_HOME

echo -n "Enter the http port for the cat server [8080]: "

read HTTP_PORT

echo -n "Enter the ajp port for the cat server [8009]: "

read AJP_PORT

echo -n "Enter the shutdown port for the cat server [8005]: "

read SHUTDOWN_PORT

echo -n "Enter the absolute path for the cat data store []: "

read DATASTORE_PATH

cat <<EOF >>setCatEnv
#!/bin/bash
export JAVA_HOME=${CAT_JAVA_HOME:-${JAVA_HOME}}
export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=512m"
EOF

chmod +x setCatEnv

cat <<EOF >>cat/conf/server.xml
<?xml version='1.0' encoding='utf-8'?>
<Server port="${SHUTDOWN_PORT:-8005}" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  <Listener className="org.apache.catalina.core.JasperListener" />
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.ServerLifecycleListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <GlobalNamingResources>
  </GlobalNamingResources>
  <Service name="Catalina">
    <Connector port="${HTTP_PORT:-8080}" protocol="HTTP/1.1" connectionTimeout="20000"/>
    <Connector port="${AJP_PORT:-8009}" protocol="AJP/1.3"/>
    <Engine name="Catalina" defaultHost="localhost">
      <Host name="localhost"  appBase="webapps" unpackWARs="true" autoDeploy="true" xmlValidation="false" xmlNamespaceAware="false"/>
    </Engine>
  </Service>
</Server>
EOF

cat <<EOF >>cat/lib/application.properties
datastore.location=${DATASTORE_PATH}
EOF
